version: '3'

services:
  broker:
    hostname: broker
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
  web:
    build: .
    hostname: web
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - broker
  worker:
    build: .
    command: sh -c "celery -A ecommerce_project worker -l info --pool=solo"
    volumes:
      - .:/app
    depends_on:
      - broker
  flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://guest:guest@broker:5672", "--port=5555"]
    ports:
      - 5555:5555
    depends_on:
      - broker